//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsDemo.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblemployee
    {
        public int emp_id { get; set; }
        
        [Required(ErrorMessage ="First Name is invalid.")]
        [RegularExpression("[a-zA-Z]+",ErrorMessage ="Only alphabets.!")]
        [Display(Name ="First Name")]
        public string f_name { get; set; }

        [Required]
        [Display(Name = "Salary")]
        public Nullable<int> salary { get; set; }

        [Required]
        [RegularExpression(@"[9876]\d{9}",ErrorMessage ="Invalid Mobile No.")]        
        public string mobile { get; set; }

        [Required]
        [EmailAddress(ErrorMessage ="Invalid Email.!")]
        public string email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [RegularExpression(@"(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[a-zA-Z!#$%&? ])[a-zA-Z0-9!#$%&?]{8,20}",ErrorMessage ="Password is Weak.")]
        public string password { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string address { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dob { get; set; }

        [Required]
        public string gender { get; set; }

        [Required]
        public Nullable<int> state_id { get; set; }

        [Required]
        public Nullable<int> city_id { get; set; }

        [Required]
        public string hobbies { get; set; }

        [Required]
        public string profileimg { get; set; }
    
        public virtual tblcity tblcity { get; set; }
        public virtual tblstate tblstate { get; set; }
    }
}
